### ISSUE TITLE
Feat: 전시 예약 기능

### ISSUE THREAD

**Issue by sangeun99** [today-exhibition/today-exhibition#11]
## Description

전시 예약 기능

## TODO

- [x]  토스 페이먼츠 기능 구현
- [x]  exhibition 적용
- [x] booking 페이지 구현
+ 추가 option
  - [ ] 성공시 QR 코드 생성
  - [ ] QR코드 인식 시 booking 정보 보여주는 페이지 구현

## ETC
Reference
- (https://developers.tosspayments.com/)

**Comment by sangeun99** [comment]
TODO
- 전시 결제 완료 후 booking, billing 테이블 업데이트되도록 수정
- 결제 완료한 전시는 조회 기능 추가
- 결제 완료 전시 바코드 만들기
