### ISSUE TITLE
Feat: 검색 기능 보완

### ISSUE THREAD

**Issue by sangeun99** [today-exhibition/today-exhibition#12]
## Description

검색 기능 보완

## TODO

- [x]  코드 함수화
- [x]  코드 인덴트 수정
- [x]  주석 추가
- [x]  json 형식으로 리턴하도록 수정
- [x] 지역 필터 세분화하여 추가하기

## ETC

**Comment by etesongg** [comment]
리스트 컴프리헨션 사용한 쿼리문은 쿼리문 인덴트 규칙 적용하지 않기
