### ISSUE TITLE
Feat: 로그인 여부 확인 데코레이터 기능 추가

### ISSUE THREAD

**Issue by cowFarmer** [today-exhibition/today-exhibition#20]
## Description
현재 session으로 user_id를 조회 후 안되면 main 혹은 login 페이지로 이동하는 함수 데코레이터로 만들어서 적용하기

## TODO
- [x] 데코레이터 기능 생성
- [x] 데코레이터 기능 적용
- [x] 기능 테스트
- [x] 좋아요, 팔로우 기능 이용시 ajax로 세션 처리
- [x] 기존 알럿창을 모달창으로 변경

**Comment by cowFarmer** [comment]
좋아요, 팔로잉 기능에 적용하려면 로직 바꿔야 합니다
확인 필요해요

**Comment by sangeun99** [comment]
좋아요, 팔로잉 기능 이용 시 javascript에 처리하도록 기능 추가해주세요 @etesongg
