### ISSUE TITLE
Design: 작가, 미술관 카드 컨포넌트 작업

### ISSUE THREAD

**Issue by sangeun99** [today-exhibition/today-exhibition#23]
## Description

작가, 미술관 카드 컨포넌트 작업

## TODO

- [x] 작가 카드 컨포넌트 작업
- [x] 미술관 카드 컨포넌트 작업
- [x] 조회 페이지에 적용

## ETC

**Comment by sangeun99** [comment]
js로 html 추가 적용 필요

**Comment by sangeun99** [comment]
카드 디폴트 이미지 만들고 적용하기
