### ISSUE TITLE
Refactor: JavaScript로 전시 상태 처리

### ISSUE THREAD

**Issue by ejnow** [today-exhibition/today-exhibition#26]
## Description
JavaScript로 전시 상태 처리

## TODO
- [ ] 작가 상세 페이지의 전시 상태 처리
- [ ] 미술관 상세 페이지의 전시 상태 처리
- [ ] 미술관 정보 누락 코드 추가
