### ISSUE TITLE
Feat: 로그인 기능 보완

### ISSUE THREAD

**Issue by sangeun99** [today-exhibition/today-exhibition#6]
## Description
로그인 기능 관련 코드 보완

## TODO
- [x] 회원탈퇴 기능 추가
- [x] 코드 리팩토링
- [x] Flask 세션 secret_key 설정
- [x] 콜백 url 환경변수로 빼기
- [x] 코드 주석 추가
- [x] 신규 로그인시 중복 닉네임이 있는 경우 random string값 부여
- [x] 회원 탈퇴시 관련 db 삭제

## ETC
- [x] 작업 완료 후 config 공유하기

Reference
- https://developers.naver.com/docs/login/devguide/devguide.md#3-4-4-%EC%A0%91%EA%B7%BC-%ED%86%A0%ED%81%B0-%EB%B0%9C%EA%B8%89-%EC%9A%94%EC%B2%AD

**Comment by cowFarmer** [comment]
- [ ] 코드 주석 추가하기
