### ISSUE TITLE
Feat: 전시, 작가, 미술관 디테일 기능 추가

### ISSUE THREAD

**Issue by sangeun99** [today-exhibition/today-exhibition#9]
## Description

전시, 작가, 미술관 디테일 기능 추가

## TODO

- [x] 디테일 페이지 내 좋아요 및 팔로우 기능
- [x] 예약하기 버튼 디자인
- [x] 미술관 디테일 페이지 : 기본 이미지 뜨도록 적용
- [x] 전시 디테일 페이지 : 작가 및 미술관 링크 걸기
- [x] 댓글 UI 개선
- [x] 코드 함수화
- [x] 코드 인덴트 수정
- [x] 주석 추가
- [x] json 형식으로 리턴하도록 수정

## ETC

할 일이 많으니 분담하여 하도록 해요
